### PR TITLE
TS: Add sourcemaps, prevent dev shutdown on error

### LINKED ISSUE #145: Dev server can't find *.ts files
Thanks for the nice template. It is really simple to get started with this. 

I have a problem when setting up the project with typescript though. I can't view the sources of my normal typescript files (with .ts extension) in the dev tools of either chrome and firefox. Chrome gives the following error message when I try to view main.ts in the Debugger:

```
Could not load content for http://localhost:5000/src/main.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```
The code within the files seems to be properly executed though. 

My first guess would be, that the code from *.ts files is not properly included in the code map.

Any help would be appreceated.

### PR DESCRIPTION
**Pull request by dummdidumm**
Add sourcemaps, fixes #145 
The original code is not inlined into the source map files by default. I guess this happens to save file sizes and because you could just as well get the code from the original file which is referenced as a relative path. For dev mode this does not work however because sirv only serves the files inside public, so inline them in that case.

Prevent shutdown on error
~~When there is a TS syntax error, the server will be shut down because the rollup plugin throws an error, because they set noEmitOnError to true by default. Change it so that this is only the case when building, not during dev.~~ EDIT: This is no longer needed because v6 of the TS plugin will no longer set `noEmitOnError`.

### CODE REVIEW

**Review by benmccann — APPROVED** [review]

**Comment by shellscape** [comment]
Note that we just merged a PR to default noEmitOnError to false. This is a breaking change and will be released in the next few days.

File: scripts/setupTypeScript.js [hunk 1]
```diff
@@ -80,7 +80,10 @@ while (( match = configEditor.exec(rollupConfig)) != null) {
 
 
 // Add TypeScript
-rollupConfig = rollupConfig.replace("commonjs(),", 'commonjs(),\n\t\ttypescript({ sourceMap: !production }),')
+rollupConfig = rollupConfig.replace(
+  'commonjs(),',
+  'commonjs(),\n\t\ttypescript({\n\t\t\tsourceMap: !production,\n\t\t\tinlineSources: !production,\n\t\t\tnoEmitOnError: production\n\t\t}),'
```
Comment (benmccann) [inline scripts/setupTypeScript.js:85]: we can upgrade to 6.0.0 which is out now and drop the `noEmitOnError` option
